#+TITLE: DesZou.github.io
#+AUTHOR: Dez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="readtheorg.css"/>

* 关于
  这是用来记录所有以后可能会用到的东西的地方，
  也是拿来好玩的。这里的 css 样式来自 http://book.emacs-china.org/。

  #+begin_src cpp
  
  #include <iostream>

  auto main() -> int {
      std::cout << "Hello, world!" << std::endl;
  
      return 0;
  }
  
  #+end_src

* 2018年
** 2月
*** 7日
    今天看到一个比较有意思的 c++ 库 [[http://cgi.di.uoa.gr/~smaragd/fc++/][fc++]] ，用 c++ 来实现函数式编程。
    毫无疑问是用到了 =template= ，这点是跑不了的，多态什么的都得靠它。
    但是让我吃惊的是它不需要用到任何新的 c++ 特性，
    官网上的测试编译器只用到了 g++3 ！
    （也说明了这个东西已经不新了）
    不过有点坑的是它没有 *任何* 标准文档，就算是英文的也比没有要强得多啊。
    但是它除了库文件之外还有一个文件夹的例子，里面有很多特性的示例，
    也许读代码比文档会更好吧。
*** 9日
    [[https://deszou.github.io/plan0209.html][寒假计划]]
*** 20日
    寒假过了，要干的事基本上就那样了。
    今天晚上还好按时到了学校（寝室没有热水），想着总得做点事，
    就抄了几道题目，好歹也是组了一套题（就是放在一起）。
    又想起我哥说的：“不用想得太多，该做的时候做就好了。”
    现在想来真是再符合我现在的困境不过了。不管怎样，
    放假就到此为止了，总得找回一点努力学习的感觉了。
    +其实这是我二十一号才写的+
*** 21日
    今天考了彭贻豪的题，三道题都是不可做的。
    第一题是一个数学题，各种奇奇怪怪的递推加上一堆定理。
    第二题是杜教筛，属于我永远想学但永远学不会的算法。
    第三题是个网络流题，二元关系模型，看上去是最好做的一道题，
    但是读题时出了点错误，搞得最后还是爆零了。 +hopeless+
*** 22日 
    今天考的谢超才的题目，画风和昨天的有很大区别。
    各种图论，数据结构之类的，唯一的共同点就是也全不会做。
    第一题是 lct 动态维护最小生成树加上线段树分治。
    第二题是图论题，关于找割点的。正解还要用到圆方树。
    第三题是概率状压 DP ，我连看都没看出来，就像自动放弃了一样。
    下午和晚上有一直在看一道 lct 的题目，终于慢慢地懂了一点。
*** 23日
    今天没有考试，好像是因为学校里回来人 *视察* 。结果什么都没看到。
    中午没有休息好，结果下午就开始头痛。又好死不死地挑了一个超级难的题，
    浪费了一个下午。晚上头痛依旧，用 Haskell 打发了时间，实在是没有什么动力。
    What a bad day~
*** 24日
    现在每天都有点拖拉，每次的内容都要丢到第二天写。
    这样下去，记这个就又没有什么用处了。晚上回家看 HP 竟然看到 1 点钟，
    我肯定是疯了，都没有什么感觉了。
*** 25日
    哇，真的不该玩到 4 点再睡的，中午竟然睡过头了！
    要不是 B 哥给老师打了电话，我恐怕得睡到 5 点去了。
    今天考的题有一道比较简单的也没做出来，不过也没什么好说的，
    人都困成这样了，还能怎么样。现在身体是真的不太好，
    没有什么精神，也涨不了肉，就是几根杆子。
    
    发现把这东西写作一个文件有一点不好：如果我要到别的电脑上加一点东西，
    就得先把原来的文件下载下来，虽然只有一个文件，
    可我不用 hexo 之类的原因就是不想配置，在哪想到就在哪可以写。
    （其实首先得有个 Emacs ）得想个像样的办法把它解决了。
*** 26日
    人生污点的考试。。。这样的弱智题竟然没做出来，脑子已经不存在了。
    现在再看 FC++ 感觉看到了屎，实现跟优雅扯不上边。
    学习了 =std::transform= 和 =std::for_each= ，希望能让代码好看点，
    毕竟我也只有这么点追求了。下午好歹吧两个弱智题改了，学习了快速幂的新姿势。
    晚上把 io 给写了，一个星期来的第一次啊，要保持下去。
*** 27日
    28 日补写。为了一个只有区间翻转的 splay tree ，花了我大半个下午加晚上，
    整个人都不好了。先是去网上搜了一波维护区间的正确姿势，然后码。。。
    结果脑子进了水，明知道要区间翻转，还去用数组随机访问节点，能对就出了鬼了。
    好吧，那就用 rank 查找吧，写起来一个函数的事。结果依旧段错误。
    结果晚上到处 debug ，左也一个错误，右也一个错误。真正的原因又出在新写的查找上，
    我忘记下传标记了。结果等题做出来了，一个晚上也结结实实花完了。
    并且最后的最后，还有一个错误：特判单点之后没有 =splay= ，
    导致一个全是单点查询的点 TLE 了。
*** 28日
    连写两天 io 。今天竟然考了我的题目，真是“受宠若惊”了，呵呵。
    托考试的福，今天上午总算撸了点正经玩意：可持久化 Treap 。
    虽然很水（那又怎么样呢），实现的还比较满意。缺点就是没有用指针，
    但是我好不容易有一个这么好写的数据结构，实在不忍心让它变复杂。
    可持久化的部分很好加入，只要把 =split= 里面的返回值变成原节点的 copy 就行了。
    
    今天还在 [[https://zh.cppreference.com][cppreference]] 里淘了会儿宝，发现了两个好东西：第一个是 =std::make_heap= ，
    =std::push_heap= ， =std::pop_heap= 这一组函数，可以用自己定义的空间维护一个堆。
    速度非常不错（至少和 =std::priority_queue= 比起来），以后再也不用手写堆了。
    PS ：好像 =std::priority_queue= 存在的原因是因为上面那组函数可能会被强制破坏堆的性质。
    可是它用了 =std::vector= 管理内存，这就让它有点鸡肋了（慢是原罪）。
    第二个是 =std::valarray= ，其实用处不会很大。但是让我知道 c++ 有这个东西心里会舒服一点。
    它本来是设计来进行数学运算的，定义了各种运算符号。让我觉得舒服的是 =std::slice= ！
    切片！ python 有的 c++ 也有！（让我有种扬眉吐气的感觉）并且在 c++98 就支持了。
    奇怪的是他没有迭代器，这让我百思不得其解，既然他也是从 =std::vector= 继承来的，
    为什么不定义一个迭代器呢？只能通过下标访问，唯一的解释就是它要和数学运算挂钩。
    （但这也不影响它加一个迭代器啊？）
