#+TITLE: DesZou.github.io
#+AUTHOR: Dez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="readtheorg.css"/>

* 关于
  这是用来记录所有以后可能会用到的东西的地方，
  也是拿来好玩的。这里的 css 样式来自 http://book.emacs-china.org/。

  #+begin_src cpp
  
  #include <iostream>

  auto main() -> int {
      std::cout << "Hello, world!" << std::endl;
  
      return 0;
  }
  
  #+end_src

* 2018年
** 2月
*** 7日
    今天看到一个比较有意思的 c++ 库 [[http://cgi.di.uoa.gr/~smaragd/fc++/][fc++]] ，用 c++ 来实现函数式编程。
    毫无疑问是用到了 =template= ，这点是跑不了的，多态什么的都得靠它。
    但是让我吃惊的是它不需要用到任何新的 c++ 特性，
    官网上的测试编译器只用到了 g++3 ！
    （也说明了这个东西已经不新了）
    不过有点坑的是它没有 *任何* 标准文档，就算是英文的也比没有要强得多啊。
    但是它除了库文件之外还有一个文件夹的例子，里面有很多特性的示例，
    也许读代码比文档会更好吧。
*** 9日
    [[https://deszou.github.io/plan0209.html][寒假计划]]
*** 20日
    寒假过了，要干的事基本上就那样了。
    今天晚上还好按时到了学校（寝室没有热水），想着总得做点事，
    就抄了几道题目，好歹也是组了一套题（就是放在一起）。
    又想起我哥说的：“不用想得太多，该做的时候做就好了。”
    现在想来真是再符合我现在的困境不过了。不管怎样，
    放假就到此为止了，总得找回一点努力学习的感觉了。
    +其实这是我二十一号才写的+
*** 21日
    今天考了彭贻豪的题，三道题都是不可做的。
    第一题是一个数学题，各种奇奇怪怪的递推加上一堆定理。
    第二题是杜教筛，属于我永远想学但永远学不会的算法。
    第三题是个网络流题，二元关系模型，看上去是最好做的一道题，
    但是读题时出了点错误，搞得最后还是爆零了。 +hopeless+
*** 22日 
    今天考的谢超才的题目，画风和昨天的有很大区别。
    各种图论，数据结构之类的，唯一的共同点就是也全不会做。
    第一题是 lct 动态维护最小生成树加上线段树分治。
    第二题是图论题，关于找割点的。正解还要用到圆方树。
    第三题是概率状压 DP ，我连看都没看出来，就像自动放弃了一样。
    下午和晚上有一直在看一道 lct 的题目，终于慢慢地懂了一点。
*** 23日
    今天没有考试，好像是因为学校里回来人 *视察* 。结果什么都没看到。
    中午没有休息好，结果下午就开始头痛。又好死不死地挑了一个超级难的题，
    浪费了一个下午。晚上头痛依旧，用 Haskell 打发了时间，实在是没有什么动力。
    What a bad day~
*** 24日
    现在每天都有点拖拉，每次的内容都要丢到第二天写。
    这样下去，记这个就又没有什么用处了。晚上回家看 HP 竟然看到 1 点钟，
    我肯定是疯了，都没有什么感觉了。
*** 25日
    哇，真的不该玩到 4 点再睡的，中午竟然睡过头了！
    要不是 B 哥给老师打了电话，我恐怕得睡到 5 点去了。
    今天考的题有一道比较简单的也没做出来，不过也没什么好说的，
    人都困成这样了，还能怎么样。现在身体是真的不太好，
    没有什么精神，也涨不了肉，就是几根杆子。
    
    发现把这东西写作一个文件有一点不好：如果我要到别的电脑上加一点东西，
    就得先把原来的文件下载下来，虽然只有一个文件，
    可我不用 hexo 之类的原因就是不想配置，在哪想到就在哪可以写。
    （其实首先得有个 Emacs ）得想个像样的办法把它解决了。
*** 26日
    人生污点的考试。。。这样的弱智题竟然没做出来，脑子已经不存在了。
    现在再看 FC++ 感觉看到了屎，实现跟优雅扯不上边。
    学习了 =std::transform= 和 =std::for_each= ，希望能让代码好看点，
    毕竟我也只有这么点追求了。下午好歹吧两个弱智题改了，学习了快速幂的新姿势。
    晚上把 io 给写了，一个星期来的第一次啊，要保持下去。
