#+TITLE: 寒假计划
#+AUTHOR: Dez
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="readtheorg.css"/>

* 概述
  还有不到两个月的时间就要省选了，对于我这种各种冬令营都没机会去的人来说。
  省选就是真正的唯一一次机会。所以假期里也不能松懈，应该根据自身的情况，
  查漏补缺。

  我在之前定下的计划里还有这么几个板块没做完：
  - 字符串
    + 后缀数组
    + 后缀自动机
    + AC 自动机
  - 数据结构
    + 动态树
    + 可持久化的数据结构

  然后线性代数也是需要继续学的，我认为这部分学到什么程度都不为过。
  还有以前总是有些东西搞不懂，现在慢慢也觉得懂了。发现当搞不懂的时候，
  不用着急或者懊恼，有时候真的是没转过弯来，那就换换环境，先做点别的。
  那种搞不懂就一定埋头硬钻的学习不太适合我。（该钻还得钻啊）

* 字符串
  我把对于单个串的字符串算法都学完了，剩下的都是多模式，多个串的算法。
  最大的区别在于 Trie 树，其实多模式就是把对单个串的操作移到 Trie 树上。
  而 Trie 本身又有一些很好的性质，一般都能和路径还有子树扯上关系。
  正因为这些性质，所以字符串处理一般都能达到线性的复杂度。（很强）

** AC 自动机
   本身就是 kmp 算法放在 Trie 树上，学长上的课上也讲过很多了。
   有些例题给出了很妙的套路，唯一没有实现的就是 *代码！！！！*
   回来之后就不应该再有这种问题了。

** 后缀 数组 / 自动机
   这部分真是知道的比较少，
   但是貌似这两个东西威力巨大，能够做出很多很强的性质出来。

* 数据结构
  动手能力，不多强调了。

** 动态树
   这个情况和上面就相反，模板什么的都会码了，用起来就各种问号，
   感觉学的东西和题目拉不出关系来。要扎实一点，把每个细节都弄懂。

** 可持久化数据结构
   打算和函数式编程一起学，期望能得到更深入的理解。
   资料什么的也搜罗的七七八八差不多了，学起来应该不会太难，
   毕竟有的以前就会了，不用从头开始能省蛮多时间。
   要注意的地方：
   - 实现的简易程度，太复杂的实现会和考试脱节
   - 实现的效率，我最近的代码跑得越来越慢了（搞不懂为什么）

* 数学
  翻来覆去就是组合和线代，说到底也就生成函数那一块难一些。
  需要大力注意的是解题时的效率问题，这部分还是看手算。
  学的东西一定不能和考试脱节，不然就都是虚的。
